classdef Anode < Electrode

    properties
        sei_resistivity
    end
    properties (Dependent)
    end

    methods
        function obj = Anode()

        end
        function s = struct(obj)
            s = struct('area',obj.area,...
                'electrode_thickness',obj.electrode_thickness,...
                'particle_radius',obj.particle_radius,...
                'volume_fraction_solid',obj.volume_fraction_solid,...
                'volume_fraction_electrolyte',obj.volume_fraction_electrolyte,...
                'diffusion_coefficient',obj.diffusion_coefficient,...
                'reaction_rate',obj.reaction_rate,...
                'intercalation_activation_energy',obj.intercalation_activation_energy,...
                'diffusion_activation_energy',obj.diffusion_activation_energy,...
                'maximum_concentration',obj.maximum_concentration,...
                'volume_fraction_filler',obj.volume_fraction_filler,...
                'specific_interfacial_area',obj.specific_interfacial_area,...
                'volume',obj.volume,...
                'molar_capacity',obj.molar_capacity,...
                'charge_capacity',obj.charge_capacity,...
                'sei_resistivity',obj.sei_resistivity);
        end
    end
end